name: Result Service

on:
    push:
        branches:
            - main
        paths:
            - "result/**"

jobs:
    result:
        uses: ./.github/workflows/build-push-update.yml
        with:
            service_name: result
        secrets: inherit
